# Generated by Django 3.0.7 on 2021-06-29 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('contact', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('email', models.EmailField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('pincode', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('gender', models.CharField(max_length=6)),
                ('education', models.CharField(max_length=25)),
            ],
        ),
    ]
